version: "3"

networks:
  fedvision-network:
    ipam:
      config:
        - subnet: 192.167.0.0/16
  
services:
  coordinator1:
    image: "federatedai/fedvision:latest"
    ports:
      - "10000"
    networks:
      fedvision-network:
        ipv4_address: 192.167.0.100
    command: ["/bin/bash", "-c", "source venv/bin/activate && python -m fedvision.framework.cli.coordinator --port 10000"]
    environment:
      - "PYTHONPATH=/data/projects/fedvision/FedVision:/data/projects/fedvision/FedVision/deps/PaddleDetection:/data/projects/fedvision/FedVision/deps/PaddleFL/python"

    
  master1:
    image: "federatedai/fedvision:latest"
    ports:
      - "10002"
    networks:
      fedvision-network:
        ipv4_address: 192.167.0.112
    command: ["/bin/bash", "-c", "source venv/bin/activate && python -m fedvision.framework.cli.master --submitter-port 10002 --party-id master1 --cluster-address '192.167.0.111:10001' --coordinator-address '192.167.0.100:10000'"]
    depends_on:
      - cluster1
      - coordinator1
    environment:
      - "PYTHONPATH=/data/projects/fedvision/FedVision:/data/projects/fedvision/FedVision/deps/PaddleDetection:/data/projects/fedvision/FedVision/deps/PaddleFL/python"


  cluster1:
    image: "federatedai/fedvision:latest"
    ports:
      - "10001"
    networks:
      fedvision-network:
        ipv4_address: 192.167.0.111
    command: ["/bin/bash", "-c", "source venv/bin/activate && python -m fedvision.framework.cli.cluster_manager --port 10001"]
    environment:
      - "PYTHONPATH=/data/projects/fedvision/FedVision:/data/projects/fedvision/FedVision/deps/PaddleDetection:/data/projects/fedvision/FedVision/deps/PaddleFL/python"


  worker1-0:
    image: "federatedai/fedvision:latest"
    ports:
      - "12000-12029"
    networks:
      fedvision-network:
        ipv4_address: 192.167.0.113
    command: ["/bin/bash", "-c", "source venv/bin/activate && python -m fedvision.framework.cli.cluster_worker --name worker1-0 --worker-ip '192.167.0.113' --port-start 12000 --port-end 12029 --max-tasks 10 --manager-address '192.167.0.111:10001' --data-base-dir /data/projects/fedvision/FedVision/data "]
    depends_on:
      - cluster1
    volumes:
    - /data/projects/fedvision/FedVision/data:/data/projects/fedvision/FedVision/data
    environment:
      - "PYTHONPATH=/data/projects/fedvision/FedVision:/data/projects/fedvision/FedVision/deps/PaddleDetection:/data/projects/fedvision/FedVision/deps/PaddleFL/python"

  worker1-1:
    image: "federatedai/fedvision:latest"
    ports:
      - "12000-12029"
    networks:
      fedvision-network:
        ipv4_address: 192.167.0.114
    command: ["/bin/bash", "-c", "source venv/bin/activate && python -m fedvision.framework.cli.cluster_worker --name worker1-1 --worker-ip '192.167.0.114' --port-start 12000 --port-end 12029 --max-tasks 10 --manager-address '192.167.0.111:10001' --data-base-dir /data/projects/fedvision/FedVision/data "]
    depends_on:
      - cluster1
    volumes:
    - /data/projects/fedvision/FedVision/data:/data/projects/fedvision/FedVision/data
    environment:
      - "PYTHONPATH=/data/projects/fedvision/FedVision:/data/projects/fedvision/FedVision/deps/PaddleDetection:/data/projects/fedvision/FedVision/deps/PaddleFL/python"



    
  master2:
    image: "federatedai/fedvision:latest"
    ports:
      - "10002"
    networks:
      fedvision-network:
        ipv4_address: 192.167.0.122
    command: ["/bin/bash", "-c", "source venv/bin/activate && python -m fedvision.framework.cli.master --submitter-port 10002 --party-id master2 --cluster-address '192.167.0.121:10001' --coordinator-address '192.167.0.100:10000'"]
    depends_on:
      - cluster2
      - coordinator1
    environment:
      - "PYTHONPATH=/data/projects/fedvision/FedVision:/data/projects/fedvision/FedVision/deps/PaddleDetection:/data/projects/fedvision/FedVision/deps/PaddleFL/python"


  cluster2:
    image: "federatedai/fedvision:latest"
    ports:
      - "10001"
    networks:
      fedvision-network:
        ipv4_address: 192.167.0.121
    command: ["/bin/bash", "-c", "source venv/bin/activate && python -m fedvision.framework.cli.cluster_manager --port 10001"]
    environment:
      - "PYTHONPATH=/data/projects/fedvision/FedVision:/data/projects/fedvision/FedVision/deps/PaddleDetection:/data/projects/fedvision/FedVision/deps/PaddleFL/python"


  worker2-0:
    image: "federatedai/fedvision:latest"
    ports:
      - "12000-12029"
    networks:
      fedvision-network:
        ipv4_address: 192.167.0.123
    command: ["/bin/bash", "-c", "source venv/bin/activate && python -m fedvision.framework.cli.cluster_worker --name worker2-0 --worker-ip '192.167.0.123' --port-start 12000 --port-end 12029 --max-tasks 10 --manager-address '192.167.0.121:10001' --data-base-dir /data/projects/fedvision/FedVision/data "]
    depends_on:
      - cluster2
    volumes:
    - /data/projects/fedvision/FedVision/data:/data/projects/fedvision/FedVision/data
    environment:
      - "PYTHONPATH=/data/projects/fedvision/FedVision:/data/projects/fedvision/FedVision/deps/PaddleDetection:/data/projects/fedvision/FedVision/deps/PaddleFL/python"

  worker2-1:
    image: "federatedai/fedvision:latest"
    ports:
      - "12000-12029"
    networks:
      fedvision-network:
        ipv4_address: 192.167.0.124
    command: ["/bin/bash", "-c", "source venv/bin/activate && python -m fedvision.framework.cli.cluster_worker --name worker2-1 --worker-ip '192.167.0.124' --port-start 12000 --port-end 12029 --max-tasks 10 --manager-address '192.167.0.121:10001' --data-base-dir /data/projects/fedvision/FedVision/data "]
    depends_on:
      - cluster2
    volumes:
    - /data/projects/fedvision/FedVision/data:/data/projects/fedvision/FedVision/data
    environment:
      - "PYTHONPATH=/data/projects/fedvision/FedVision:/data/projects/fedvision/FedVision/deps/PaddleDetection:/data/projects/fedvision/FedVision/deps/PaddleFL/python"
